package utils

import (
	"math/rand"
)

func SelectRandomTicker() (string, string) {
	// make this a dict with format tickerName: tickerSymbol or vice versa
	tickerDict := map[string]string{
		"AAPL":  "Apple",
		"GOOGL": "Alphabet A",
		"AMZN":  "Amazon.com",
		"META":  "Meta Platforms",
		"NVDA":  "NVIDIA",
		"TSLA":  "Tesla",
		"MSFT":  "Microsoft",
		"NFLX":  "Netflix",
		"CRM":   "Salesforce",
		"CAT":   "Caterpillar",
		"V":     "Visa",
		"MA":    "Mastercard",
		"AXP":   "American Express",
		"KO":    "Coca-Cola",
		"MCD":   "McDonald's",
		"CMG":   "Chipotle Mexican Grill",
		"DIS":   "Walt Disney Co",
		"VZ":    "Verizon Communications",
		"CVX":   "Chevron",
		"XOM":   "Exxon Mobil",
		"OXY":   "Occidental Petroleum",
		"PWR":   "Quanta Services",
		"CSCO":  "Cisco Systems",
		"ORCL":  "Oracle",
		"INTU":  "Intuit",
		"ADBE":  "Adobe",
		"DELL":  "Dell Technologies",
		"AVGO":  "Broadcom",
		"AMD":   "Advanced Micro Device",
		"SMCI":  "Super Micro Computer",
		"KLAC":  "KLA Corp",
		"TSM":   "Taiwan Semiconductor Mfg.",
		"MRVL":  "Marvell Technology",
		"MU":    "Micron Technology",
		"ARM":   "Arm Holdings PLC",
		"SNPS":  "Synopsys",
		"AMAT":  "Applied Materials",
		"QQQ":   "Invesco QQQ Trust Series 1",
		"TQQQ":  "ProShares UltraPro QQQ",
		"ASML":  "ASML Holding NV",
		"WM":    "Waste Management",
		"GE":    "General Electric",
		"GS":    "Goldman Sachs Group Inc",
		"BLK":   "BlackRock",
		"JPM":   "JPMorgan Chase",
		"MS":    "Morgan Stanley",
		"APO":   "Apollo Global Management A",
		"ACN":   "Accenture Plc",
		"PGR":   "Progressive Corp",
		"ALL":   "Allstate Corp",
		"BKNG":  "Booking Holdings",
		"EXPE":  "Expedia Group",
		"ABNB":  "Airbnb",
		"UAL":   "United Airlines Holdings",
		"DAL":   "Delta Air Lines",
		"LLY":   "Eli Lilly And Co",
		"UNH":   "UnitedHealth Group",
		"VRTX":  "Vertex Pharmaceuticals Incorporated",
		"MMM":   "3M Co",
		"ABT":   "Abbot Laboratories",
		"ALGN":  "Align Technology",
		"ISRG":  "Intuitive Surgical",
		"SHOP":  "Shopify Inc",
		"TEAM":  "Atlassian Corp",
		"PANW":  "Palo Alto Networks",
		"F":     "Ford Motor",
		"GM":    "General Motors",
		"RACE":  "Ferrari NV",
		"ORLY":  "O'Reilly Automotive",
		"CPRT":  "Copart",
		"CTAS":  "CTAS",
		"LOW":   "Lowe's",
		"HD":    "Home Depot",
		"PSX":   "Phillips 66",
		"CMI":   "Cummins",
		"SHW":   "Sherwin-Williams",
		"COST":  "Costco",
		"WMT":   "Walmart",
		"KR":    "Kroger",
		"JNJ":   "Johnson & Johnson (J&J)",
		"PFE":   "Pfizer",
		"WBA":   "Walgreens Boots Alliance",
		"CVS":   "CVS Health Corp",
		"TGT":   "Target",
		"TOL":   "Toll Brothers",
		"DDS":   "Dillards",
		"ANF":   "Abercrombie & Fitch",
		"JWN":   "Nordstrom",
		"ELF":   "ELF Beauty",
		"ULTA":  "Ulta Beauty",
		"EL":    "Estee Lauder",
		"OXM":   "Oxford Industries",
		"DG":    "Dollar General",
		"DPZ":   "Domino's Pizza Inc",
		"WING":  "Wingstop Inc",
		"YUM":   "Yum! Brands",
		"LW":    "Lamb Weston Holdings",
		"BLD":   "Topbuild Corp",
		"DHI":   "DR Horton",
		"DKS":   "Dick's Sporting Goods",
		"BBY":   "Best Buy",
		"ETSY":  "Etsy Inc",
		"DASH":  "DoorDash",
	}

	i := 0
	tickerList := make([]string, len(tickerDict))
	for k := range tickerDict {
		tickerList[i] = k
		i++
	}

	randomIndex := rand.Intn(len(tickerList))
	randTickVal := tickerList[randomIndex]
	randTickName := tickerDict[randTickVal]
	return randTickVal, randTickName
}
